In [1]:
# Standard imports
from pprint import pprint

# Third-party imports
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Project imports
import twinlab as tl

          ====== TwinLab Client Initialisation ======
          Version     : 2.4.0
          Server      : https://x1wx0cskd1.execute-api.eu-west-2.amazonaws.com/dev
          Environment : /Users/sergiochavez/twinlab-demos/.env

In [3]:
tl.list_emulators(verbose=True)

Successfully trained emulators:
[{'model': 'example_emulator0',
  'run_time': '0:00:07',
  'start_time': '2024-03-12 11:54:07'},
 {'model': 'example_emulator',
  'run_time': '0:00:07',
  'start_time': '2024-03-12 13:13:10'},
 {'model': 'SimpleGP',
  'run_time': '0:00:06',
  'start_time': '2024-03-18 17:51:22'},
 {'model': 'emulator',
  'run_time': '0:00:14',
  'start_time': '2024-03-19 11:02:16'}]
Emulators that failed to train:
[{'model': '0', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '1', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '10', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '11', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '12', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '13', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '14', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '15', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '16', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '17', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '18', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '19', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '2', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '20', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '21', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '22', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '23', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '24', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '25', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '26', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '27', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '28', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '29', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '3', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '30', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '31', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '32', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '33', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '34', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '35', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '36', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '37', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '38', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '39', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '4', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '40', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '41', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '42', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '43', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '44', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '45', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '46', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '47', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '48', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '49', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '5', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '6', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '7', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '8', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': '9', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': 'Batman4_model', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': 'Batman4_model', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': 'Batman4_model', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': 'Sergio_emulator', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': 'Sergio_emulator', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': 'Sergio_emulator', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': 'Sergio_emulator', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': 'Sergio_emulator', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': 'Sergio_emulator', 'run_time': 'NaN', 'start_time': 'NaN'},
 {'model': 'Sergio_emulator', 'run_time': 'NaN', 'start_time': 'NaN'}]

['0',
 '1',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '2',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '3',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '4',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '5',
 '6',
 '7',
 '8',
 '9',
 'Batman4_model',
 'Batman4_model',
 'Batman4_model',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'SimpleGP',
 'emulator',
 'example_emulator',
 'example_emulator0']

In [7]:
tl.load_example_dataset("biscuits")

Dataframe downloaded successfully

,Pack price [GBP],Number of biscuits per pack,Number of packs sold,Profit [GBP]
0,2.30,20,2385,16695.0
1,2.25,20,2553,16594.5
2,2.00,18,2812,15747.2
3,1.80,16,2647,13764.4
4,1.90,16,2755,17081.0
5,1.95,16,2642,17701.4
6,2.20,18,2516,19121.6
7,2.00,20,2886,11544.0
8,2.05,20,2964,13338.0
9,2.10,20,2839,14195.0
10,1.80,20,3438,6876.0
11,1.90,18,2887,13280.2

In [1]:
import twinlab as tl
emulator = tl.Emulator(id="biscuits")

          ====== TwinLab Client Initialisation ======
          Version     : 2.4.0
          Server      : https://x1wx0cskd1.execute-api.eu-west-2.amazonaws.com/dev
          Environment : /Users/sergiochavez/twinlab-demos/.env

In [10]:
new_data=emulator.view_test_data()

In [14]:
new_data

,Pack price [GBP],Number of biscuits per pack,Number of packs sold,Profit [GBP]
0,2.1,20.0,2839.0,14195.0
1,1.8,20.0,3438.0,6876.0
2,1.9,18.0,2887.0,13280.2

In [15]:
emulator.sample(df=new_data, num_samples=100)

  Number of packs sold                                                      \
                     0            1            2            3            4
0          2883.727298  2876.618932  2821.004313  2899.902807  2855.102440
1          2864.023637  2705.886550  2535.313982  2568.191737  2818.764578
2          3002.282088  2805.628886  2533.491136  2743.266185  2762.078415

                                                                    ...  \
             5            6            7            8            9  ...
0  2901.025429  2984.972884  2871.436081  2877.397589  2809.561791  ...
1  2764.094457  2570.132844  2769.739830  2686.350451  2745.614113  ...
2  2668.007999  2722.972562  2831.513664  2917.885932  2824.860142  ...

   Profit [GBP]                                                          \
             90            91            92            93            94
0  15822.624085  14208.323075  15497.261213  14875.276158  14031.456655
1  14469.888085  14439.421095  13516.748810  15604.508831  10265.988911
2  16675.010885  17089.629467  15903.293394  12409.213492  14235.763437


             95            96            97            98            99
0  15113.378444  14026.947933  14287.091677  14669.918312  14882.215283
1   7326.363171  14109.731795  10515.353460   9743.867597  12427.835213
2  13853.280041  13638.063149  13066.413803  16588.376046  14875.094022

[3 rows x 200 columns]

# FIXING DATAFRAME IN SAMPLE MULTIFIDELITY & BOUND

## Reproduce the error

In [1]:
import twinlab as tl

          ====== TwinLab Client Initialisation ======
          Version     : 2.4.0
          Server      : https://x1wx0cskd1.execute-api.eu-west-2.amazonaws.com/dev
          Environment : /Users/sergiochavez/twinlab-demos/.env

In [1]:
import pandas as pd
import numpy as np
import twinlab as tl

#If running from the stack, run
# dataset_path = os.path.join(resources_path, "datasets", "multi_fidelity.csv") 
# df = tl.load_dataset(dataset_path)
df = tl.load_dataset("multi_fidelity.csv")
dataset = tl.Dataset(id="multi_fidelity")
dataset.upload(df)

# Create and train emulator
estimator_params = tl.EstimatorParams(estimator_type="multi_fidelity_gp")
params = tl.TrainParams(
        train_test_ratio=0.8,
        estimator_params=estimator_params,
        seed=123,
        fidelity="fidelity",
    )
emulator = tl.Emulator(id="multi_fidelity")
emulator.train(dataset, inputs=["x"], outputs=["y"], params=params)

          ====== TwinLab Client Initialisation ======
          Version     : 2.4.0
          Server      : https://x1wx0cskd1.execute-api.eu-west-2.amazonaws.com/dev
          Environment : /Users/sergiochavez/twinlab-demos/.env

In [3]:
# Sampling
sample_params = tl.SampleParams(
        seed=123,
        fidelity=pd.DataFrame({"fidelity": np.hstack((np.ones(5), 0.5 * np.ones(15)))}),
    )
X = np.linspace(0, 1, 20)
input_df = pd.DataFrame({"x": X})
sample_df = emulator.sample(input_df, num_samples=2, params=sample_params)

In [13]:
# Sampling
sample_params = tl.SampleParams(
        seed=123,
        # fidelity=pd.DataFrame({"fidelity": np.hstack((np.ones(5), 0.5 * np.ones(15)))}),
    )
X = np.linspace(0, 1, 20)
input_df = pd.DataFrame({"x": X})
sample_df = emulator.sample(input_df, num_samples=2, params=sample_params)

AttributeError: 'SampleParams' object has no attribute 'fidelity'

In [11]:
sample_df

            y
            0          1
0    3.452415   3.098812
1    0.382766   0.463910
2   -0.724362  -0.746020
3   -0.750073  -1.149959
4   -0.606426  -0.481819
5   -0.557702  -0.109540
6    0.224879   0.313103
7    0.964966   0.492732
8    0.301059   0.230377
9    0.910147   0.499680
10   0.425342   1.219239
11  -2.108685   1.555997
12  -2.440346   1.340844
13  -0.759846  -0.590895
14  -1.085941  -2.947949
15  -2.531255  -3.175562
16  -1.532837  -0.976675
17   4.864041   5.105267
18  12.097988  12.783014
19  16.105898  15.160377